### ISSUE TITLE
Falla desde windows

### ISSUE THREAD

**Issue by Deivid11213** [ivansaul/codigo_facilito_downloader#1]
de la nada se cierra antes de descargar todo y no guarda los cursos adjunto ahi el error que deja
![Captura de pantalla 2023-06-13 121844](https://github.com/ivansaul/codigo_facilito_downloader/assets/107719115/941254c3-e063-4a6d-96ce-a408881f1c6c)

**Comment by ivansaul** [comment]
@Deivid11213 ya tiene soporte tanto para windows y mac.

**Comment by Deivid11213** [comment]
Como te va Iván la verdad esta chévere tu script ayer me funciono solo que a veces los cursos por ejemplo en una clase hay 17 cursos y descarga solo 15 cursos de 17 no se si me entiendes pero eso es el error al descargar descarga todo los cursos pero algunas clases no.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

**Comment by ivansaul** [comment]
@Deivid11213 No todas las clases son de vídeo. Algunas solo tiene unas notas. Eso no lo implemente, ya que me pareció irrelevante. Pero si la gente lo pide en la próxima versión lo implementare.
