### ISSUE TITLE
Error al descargar [No existe data.json]

### ISSUE THREAD

**Issue by zVeztw** [ivansaul/codigo_facilito_downloader#10]
Curso al descargar: https://codigofacilito.com/cursos/flutter-profesional

Error:
Leyendo las credenciales ...
Getting cookies.txt ...
Traceback (most recent call last):
  File "C:\Users\Cliente\Desktop\FINAL\codigo_facilito_downloader-master\downloader.py", line 86, in <module>
    main()
  File "C:\Users\Cliente\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cliente\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Cliente\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cliente\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cliente\Desktop\FINAL\codigo_facilito_downloader-master\downloader.py", line 82, in main
    dl.load_data()
  File "C:\Users\Cliente\Desktop\FINAL\codigo_facilito_downloader-master\downloader.py", line 17, in load_data
    with open(self.data_path, 'r', encoding = 'utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data.json'
[Finished in 2.7s with exit code 1]

**Comment by eber05** [comment]
Me encontré con el mismo problema que tu, revisé la versión 1.0 que el desarrollador había liberado y me percaté que estamos omitiendo un paso debido a que el desarrollador en la versión 3.0 omitió explicar que ese paso es fundamental. Y es la parte de instalar la [extensión](https://chrome.google.com/webstore/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc/related)  en el navegador (Brave o Chrome). Después de instalarla, inicia sesión, entra al curso, reproduce un video y copia las cookies de la extensión en el archivo cookies.txt.
En este [video](https://www.youtube.com/watch?v=GbQwB0hYvQU) muestra cómo hacerlo... Sigue sus pasos.
Estoy usando Windows 10 y Python 3.7.
La instrucción que funcionó para mi a la hora de descargar, fue esta: `python downloader.py -d yt-dlp -q 1080`

**Comment by ivansaul** [comment]
@eber05 @zVeztw  Es probable que sea necesario realizar mantenimiento en el código. Sin embargo, con la última versión liberada, ya no sería necesario crear manualmente las cookies mediante la extensión, ya que el script las generaría automáticamente.

**Comment by eber05** [comment]
Probablemente si, porque en mi caso lo intenté sin generar las cookies en el archivo y no me estaba funcionando, o dudo si lo estaba haciendo bien, Agradezco la aclaración, pero aún así me sirvió mucho el video de referencia en las versiones previas liberadas, aunque en la versión más reciente, la velocidad de descarga es muy superior!

**Comment by eber05** [comment]
@ivansaul Tienes razón, el motivo por el que no estaba funcionando es porque al ingresar el comando `python facilito.py` e inglresar la URL del curso, estaba ingresando una url como esta: 
[https://codigofacilito.com/cursos/english-for-devs-2](https://codigofacilito.com/cursos/english-for-devs-2)
cuando ingresé a reproducir los cursos de esta forma, funciono sin problema!
[https://codigofacilito.com/videos/recapitulacion-de-temas](https://codigofacilito.com/videos/recapitulacion-de-temas)
Gracias =D!
