### ISSUE TITLE
falta actualizar script

### ISSUE THREAD

**Issue by CarlosCab061** [ivansaul/codigo_facilito_downloader#13]
podrías actualizar el script, ya no funciona, creo que código facilito cambio la estructura de su pagina.

**Comment by ivansaul** [comment]
@CarlosCab061  deja mas contexto para poder replicar el error

**Comment by CarlosCab061** [comment]
> @CarlosCab061 deja mas contexto para poder replicar el error

![cats](https://github.com/ivansaul/codigo_facilito_downloader/assets/39539574/f3ee1d9c-1916-4e51-8d4f-297ca5f9a157)

**Comment by CodeGeekR** [comment]
parece que los XPatch se han actualizado en la web de codigofacilito.

**Comment by ivansaul** [comment]
@CarlosCab061 @CodeGeekR solo falta actualizar en `cookies.py` el bypass de cloudflare ya se implemento en el ultimo commit

**Comment by ivansaul** [comment]
@CarlosCab061 @CodeGeekR actualiza al ultimo commit ya se corrigieron todos los errores en la rama master.
