### ISSUE TITLE
error al ejecutar facilito.py

### ISSUE THREAD

**Issue by adrian-reina-391** [ivansaul/codigo_facilito_downloader#14]
obtengo este error luedo de ejectutar facilito.py
PS C:\Users\ADRIAN\codigo_facilito_downloader> python.exe facilito.py
Leyendo las credenciales ...
Ingresa la URL del curso a descargar: https://codigofacilito.com/videos/introduccion-39ac0921-87e7-47ab-b39e-7a86e534be3f
Traceback (most recent call last):
  File "C:\Users\ADRIAN\codigo_facilito_downloader\facilito.py", line 147, in <module>
    facilito.login()
  File "C:\Users\ADRIAN\codigo_facilito_downloader\facilito.py", line 47, in login
    wait.until(EC.presence_of_element_located((By.XPATH, '//div[@class="users-nav"]')))
  File "E:\Program Files\Python\Lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16

PS C:\Users\ADRIAN\codigo_facilito_downloader>

**Comment by pberus** [comment]
Me sucede lo mismo, probe todas las sugerencias que dijeron y me sigue pasando.

**Comment by adrian-reina-391** [comment]
> Me sucede lo mismo, probe todas las sugerencias que dijeron y me sigue pasando.

Yo he probado muchísimas cosas y configuraciones y sigue dando ese error, antes no me pasaba eso

**Comment by Daldude1** [comment]
Hola! el problema es por culpa de CloudFlare, lo solucioné en mi pc y subiré un PullRequest pronto :)

**Comment by ivansaul** [comment]
@adrian-reina-391 @Daldude1 @pberus actualiza al ultimo commit ya se corrigieron todos los errores en la rama master.
