### ISSUE TITLE
Los videos descargados no tienen audio

### ISSUE THREAD

**Issue by JoaGamo** [ivansaul/codigo_facilito_downloader#15]
Buenas, estuve arreglando y debuggeando el codigo, pero no consigo tener audio junto con el video
Bajé la branch feature/cloudflare

Mis modificaciones fueron:
Obtuve cookies.txt a traves de una extensión de firefox, debido a que getCookies() no me andaba correctamente
comenté get_course_id() retornando manualmente la ID del curso leyendo el codigo html (en mi caso, "206"). No sé programar python, así que esta fue una solución temporal para poder ejecutar facilito.py y obtener el data.json

Con el data.json ya obtenido, en este caso el del enlace mostrado en el readme, https://codigofacilito.com/videos/introduccion-al-curso-profesional-de-backend, debido a que me tiraba el mismo error de #12 (Forbidden 403) decidi ejecutar el comando que ejecutaría el downloader.py manualmente.

especificamente:

`yt-dlp -f 2623 --cookies cookies.txt -o videotesting https://video-storage.codigofacilito.com/hls/206/6902/playlist.m3u8`

De esta forma, durante este debugging, se puede obtener el video pero no logro conseguir audio. Incluso listando los formatos con -F (o --list-formats), el formato de solo-audio no descarga nada

**Comment by ivansaul** [comment]
@JoaGamo actualiza al ultimo commit ya se corrigieron todos los errores en la rama master.
