### ISSUE TITLE
Al ejecutar facilito.py, el script se detiene al momento de navegar en la pantalla del curso

### ISSUE THREAD

**Issue by DanielCovarrubias** [ivansaul/codigo_facilito_downloader#16]
¡Buenos días a todos! 

Al ejecutar facilito.py, obtengo el siguiente error:

Ingresa la URL del curso a descargar: https://codigofacilito.com/videos/introduccion-9d412c2d-bb1b-4b19-b2f8-9055f0cdc9b8
Logging in ...
Getting course content ...
Traceback (most recent call last):
  File "C:\Users\Daniel\codigo_facilito_downloader\facilito.py", line 149, in <module>
    facilito.get_course_content()
  File "C:\Users\Daniel\codigo_facilito_downloader\facilito.py", line 83, in get_course_content
    drop.click()
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (1815, 1143)
  (Session info: chrome=119.0.6045.160)
Stacktrace:
        GetHandleVerifier [0x00A872A3+45731]
        (No symbol) [0x00A12D51]
        (No symbol) [0x0090880D]
        (No symbol) [0x009407AB]
        (No symbol) [0x0093F2AF]
        (No symbol) [0x0093D89B]
        (No symbol) [0x0093CBA1]
        (No symbol) [0x00934FC0]
        (No symbol) [0x00957FDC]
        (No symbol) [0x00934A4E]
        (No symbol) [0x00958254]
        (No symbol) [0x0096B7A2]
        (No symbol) [0x00957DD6]
        (No symbol) [0x009331F6]
        (No symbol) [0x0093439D]
        GetHandleVerifier [0x00D90716+3229462]
        GetHandleVerifier [0x00DD84C8+3523784]
        GetHandleVerifier [0x00DD214C+3498316]
        GetHandleVerifier [0x00B11680+611968]
        (No symbol) [0x00A1CCCC]
        (No symbol) [0x00A18DF8]
        (No symbol) [0x00A18F1D]
        (No symbol) [0x00A0B2C7]
        BaseThreadInitThunk [0x74FAFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77157C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77157C3E+238]

Lo que ocurre con el navegador, es que, se loguea automáticamente con el correo y contraseña de la cuenta, ingresa al curso, pero noto que se intenta clickear en el menú donde están los cursos, y justamente en ese momento, se detiene y obtengo el error de arriba. Estoy ejecutando la rama de feature/cloudflare

¡Saludos!

**Comment by eliottp1089** [comment]
> Se soluciona haciendo scroll, cuando se van desplegando los modulos, no debes pasarte porque si te pasas con el scroll igual marca error.
> 
> Yo le hice ciertas mejoras al script, como nombrar las carpetas de modulos con su respectivo nombre ej: Modulo 1 - Introduccion, pero por desconocimiento descargue solo la rama cloudflare.

Que codigo ulizaste para agg el nombre de los módulos?

**Comment by Ronald3217** [comment]
> > Se soluciona haciendo scroll, cuando se van desplegando los modulos, no debes pasarte porque si te pasas con el scroll igual marca error.
> > Yo le hice ciertas mejoras al script, como nombrar las carpetas de modulos con su respectivo nombre ej: Modulo 1 - Introduccion, pero por desconocimiento descargue solo la rama cloudflare.
> 
> Que codigo ulizaste para agg el nombre de los módulos?

Ya se agrego al codigo del repositorio, actualizalo. Esta en la rama "feature/cloudflare"

**Comment by eliottp1089** [comment]
> > > Se soluciona haciendo scroll, cuando se van desplegando los modulos, no debes pasarte porque si te pasas con el scroll igual marca error.
> > > Yo le hice ciertas mejoras al script, como nombrar las carpetas de modulos con su respectivo nombre ej: Modulo 1 - Introduccion, pero por desconocimiento descargue solo la rama cloudflare.
> > 
> > 
> > Que codigo ulizaste para agg el nombre de los módulos?
> 
> Ya se agrego al codigo del repositorio, actualizalo. Esta en la rama "feature/cloudflare"

Ya actualice bro ahora tengo un problema, cuando utilizo aria2c como downloader solo descarga el video y cuando pasa a descargar el audio nuestra error 403, vuelvo a ejecutar el downloader.py y baja el audio y así sigue en lo mismo, cuando quito aria2c funciona bien

**Comment by ivansaul** [comment]
@DanielCovarrubias actualiza al ultimo commit ya se corrigieron todos los errores en la rama master.
