### ISSUE TITLE
downloader.py en windows 

### ISSUE THREAD

**Issue by adrian-reina-391** [ivansaul/codigo_facilito_downloader#2]
quizás estoy haciendo algo mal pero cuando llega la parte de descargar las lecciones me da error 403
![issue facilito](https://github.com/ivansaul/codigo_facilito_downloader/assets/55458805/45b19159-b306-42b7-8746-8081dd7a11be)
quizás sea obvio, pero un video explicando desde 0 para windows pudiera ser útil, y luego para la segunda vez porque a mi entender lo estoy haciendo todo bien pero algún error debo tener, ffmpeg esta instalado, firefox, python, y yt-dlp está instalado desde la consola así que tiene que estar actualizado también

**Comment by ivansaul** [comment]
@adrian-reina-391este error te está dando ya que no tienes actualizado las cookies. Entra a uno de los videos del curso que deseas descargar y desde allí copias las cookies y pegalo en `cookies.txt`
