### ISSUE TITLE
Error al descargar 

### ISSUE THREAD

**Issue by duver88** [ivansaul/codigo_facilito_downloader#21]
![WhatsApp Image 2024-01-21 at 12 41 35 AM](https://github.com/ivansaul/codigo_facilito_downloader/assets/30910562/e2a35d04-f869-471b-9290-6f4a9b0b09c7)
Tengo el siguiente error al intentar descargar los archivos gracias de ante mano

**Comment by ivansaul** [comment]
@duver88 brinda mas detalles para poder reproducir el error, como por ejemplo curso, la url, ...
Al parecer el error lo esta generando las cookies, probablemente ya expiraron. Tienes que volver a actualizar el `cookies.txt` y nuevamente ejecutar `python downloader.py`

**Comment by duver88** [comment]
https://codigofacilito.com/videos/presentacion-del-curso-de-javascript
Hay que tener una suscripción?

**Comment by ivansaul** [comment]
@duver88 el error se debe a que no tienes instalado correctamente todas sus dependencias [LEER](https://github.com/ivansaul/codigo_facilito_downloader?tab=readme-ov-file#windows). En este caso especificamente `yt-dlp`. 
Para instalarlo, en la raíz de proyecto ejecuta `pip install -U yt-dlp`

**Comment by duver88** [comment]
Si estas en lo correcto disculpa
