### ISSUE TITLE
Error a ejecutar python3 favilito.py

### ISSUE THREAD

**Issue by tjaoc** [ivansaul/codigo_facilito_downloader#23]
![Captura de pantalla 2024-01-23 a las 8 35 29](https://github.com/ivansaul/codigo_facilito_downloader/assets/6704635/4f8700e7-81b6-402a-9d43-a3bab6f5f9c4)

**Comment by ivansaul** [comment]
@tjaoc la url no es la correcta, tienes que pasarle la url de cualquier video del curso como por ejemplo `https://codigofacilito.com/videos/1-introduccion ....`
