### ISSUE TITLE
Problema al descargar despues de utilizar bootcamp.py

### ISSUE THREAD

**Issue by davidal07** [ivansaul/codigo_facilito_downloader#25]
Hola,
despues de ejecutar el script de bootcamp.py se guarda un archivo bootcamp.json,
luego ejecuto downloader.py y este script sigue buscando un archivo llamado data.json.

Es necesario cambiar algo para que no suceda esto o estoy haciendo mal el procedimiento?

**Comment by ivansaul** [comment]
#20
