### ISSUE TITLE
¿Cómo desgargar en lote? 

### ISSUE THREAD

**Issue by Santiagoc57** [ivansaul/codigo_facilito_downloader#28]
De ante mano me diculpo por que capaz ya es claro para muchos con la explicacion pero yo no he podido aun siguiendo los pasos. Lo que quiero hacer es descagar un bootcamp lo mas rapido posible, los pasos que segui fue.

1. Ejecutar bootcamp.py con la url del curso en general, una vez ejuctado entro al archivo bootcam.json y alli estan listados todos los modulos que contiene el curso y su respectiva url.
2. Acto seguido (aca es donde me pierdo)
¿Tengo copiar una a una la url de esos modulos (diagmos que son 10) cuando ejecuto facilito.py y posteriormente ejecutar downloader.py (ejecutarlo 10 veces)?

O acaso hay alguna forma de cargarlos todos y descarlos en lote? De ante mano muchas gracias y agadezo su ayuda soy inexperto y avaces me cuesta este tipo de cosas.

**Comment by ivansaul** [comment]
#20 
de momento no es posible hacer por lote. para la próxima version probablemente.

**Comment by Ronald3217** [comment]
> ver #20 de momento no es posible hacer por lote. para la próxima versión probablemente.

Hola, hice una funcionalidad para descargar en lote, por ahora la he probado con 2 cursos y no tuve problema (dejando de lado lo de actualizar las cookies). Te hice la pull request

**Comment by ivansaul** [comment]
@Ronald3217 vale perfecto.
