### ISSUE TITLE
Error! Thats not a valid [VIDEO|COURSE] URL

### ISSUE THREAD

**Issue by AugustoPCortes** [ivansaul/codigo_facilito_downloader#34]
hola al ingresar la url en la version  coco  responde Error! Thats not a valid [VIDEO|COURSE] URL  gracias

**Comment by ivansaul** [comment]
@AugustoPCortes  haz un buen reporte, uno no es adivino. tienes que dar mas contexto.
lo único que te puedo decir es practicamente lo mismo. **`No es un enlace valido`**.
