### ISSUE TITLE
Error en windows

### ISSUE THREAD

**Issue by brayandev16** [ivansaul/codigo_facilito_downloader#4]
Me sale un error al tratar de descargar los videos, cumplí con los requisitos, instalé ffmpeg y yt-dlp, también firefox, 
![image](https://github.com/ivansaul/codigo_facilito_downloader/assets/94092722/b266f00a-0e97-4017-b684-50ea93f0078c)

segun chatgpt el error se debe que no está instalado yt-dlp, pero ya ejecuté "pip install -U yt-dlp", y aun nada, dejaré la acptura también de lo que me sale cuando ejecuto "pip install -U yt-dlp"
![image](https://github.com/ivansaul/codigo_facilito_downloader/assets/94092722/99ec8478-2b6a-4f4c-ba09-0e467e299179)

y algo raro que noté es que no me sale la lista de videos igual que al resto.
![image](https://github.com/ivansaul/codigo_facilito_downloader/assets/94092722/f027b294-890c-4ebb-9d88-51911a096b2a)

De ante mano, gracias por tomarte el tiempo de leer, espero me ayudes.

**Comment by ivansaul** [comment]
@brayandev16 al pareces no guardaste las cookies en `cookies.txt`

**Comment by CarlosCab061** [comment]
yo utilizé la extension para firefox llamada **cookies.txt**, el unico que me funciono.

**Comment by brayandev16** [comment]
@ivansaul  Si tengo las cookies ahí en el txt mira, asi está.
![image](https://github.com/ivansaul/codigo_facilito_downloader/assets/94092722/9fa7c29c-a035-4d58-b1bd-99352ff6459e)

**Comment by ivansaul** [comment]
@brayandev16 escribeme al chat de discord a ver si puedo ayudarte.  [![Discord](https://img.shields.io/badge/-Discord-424549?style=social&logo=discord)](https://discord.gg/b72uAVBz6b)
