### ISSUE TITLE
No inicia sesión

### ISSUE THREAD

**Issue by ederUp** [ivansaul/codigo_facilito_downloader#49]
Presenta problemas para iniciar sesión, se queda colgado en la verificación si es un robot:
![Captura de pantalla 2024-11-23 175005](https://github.com/user-attachments/assets/6b136d8f-5cd5-4d77-9053-75ce1e3ebf84)
De ahí no pasa y se cierra automaticamente.

**Comment by ivansaul** [comment]
@ederUp en la version 0.3.0 se introdujo un nuevo comando para iniciar session usando cookies.
